# Generated by Django 5.2.2 on 2025-06-08 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteKalaCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('faixa_etaria', models.IntegerField(choices=[(1, '< 12 meses'), (2, '12-23 meses'), (3, '2-15 anos'), (4, '16-40 anos'), (5, '> 40 anos')])),
                ('sitios_sangramento', models.IntegerField(choices=[(1, 'Nenhum'), (2, '1-2 sítios'), (3, '3-4 sítios'), (4, '5-6 sítios')])),
                ('edema', models.BooleanField(default=False)),
                ('aids', models.BooleanField(default=False)),
                ('ictericia', models.BooleanField(default=False)),
                ('dispneia', models.BooleanField(default=False)),
                ('infeccao', models.BooleanField(default=False)),
                ('vomitos', models.BooleanField(default=False)),
                ('leucopenia', models.BooleanField(default=False)),
                ('plaquetopenia', models.BooleanField(default=False)),
                ('insuficiencia_renal', models.BooleanField(default=False)),
                ('hepatite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente KalaCal',
                'verbose_name_plural': 'Pacientes KalaCal',
            },
        ),
        migrations.CreateModel(
            name='CalculoKalaCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_usado', models.CharField(choices=[('clinico', 'Clínico'), ('clinico_laboratorial', 'Clínico e Laboratorial')], max_length=30)),
                ('escore', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)])),
                ('probabilidade_morte', models.FloatField(help_text='Probabilidade de morte em %')),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='kalacal_calculator.pacientekalacal')),
            ],
            options={
                'verbose_name': 'Cálculo KalaCal',
                'verbose_name_plural': 'Cálculos KalaCal',
                'ordering': ['-calculado_em'],
            },
        ),
    ]
