# Generated by Django 5.2.2 on 2025-06-08 14:06

from django.db import migrations

def delete_existing_data(apps, schema_editor):
    """Delete existing KalaCal data before structural changes"""
    CalculoKalaCal = apps.get_model('kalacal_calculator', 'CalculoKalaCal')
    PacienteKalaCal = apps.get_model('kalacal_calculator', 'PacienteKalaCal')
    
    CalculoKalaCal.objects.all().delete()
    PacienteKalaCal.objects.all().delete()

def reverse_delete_data(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('kalacal_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_existing_data, reverse_delete_data),
    ]
