# Generated by Django 5.2.2 on 2025-06-08 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_caso_aids_caso_dispneia_caso_edema_and_more'),
        ('kalacal_calculator', '0002_auto_20250608_1106'),
    ]

    operations = [
        # Remove o modelo PacienteKalaCal completamente
        migrations.DeleteModel(
            name='PacienteKalaCal',
        ),
        
        # Remove o campo paciente do CalculoKalaCal
        migrations.RemoveField(
            model_name='calculokalacal',
            name='paciente',
        ),
        
        # Adiciona o campo caso
        migrations.AddField(
            model_name='calculokalacal',
            name='caso',
            field=models.ForeignKey(
                default=1,  # Temporário - será ajustado depois
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calculos_kalacal',
                to='casos.caso'
            ),
            preserve_default=False,
        ),
        
        # Adiciona o campo observacoes
        migrations.AddField(
            model_name='calculokalacal',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o cálculo'),
        ),
    ]
