# Generated by Django 5.2.2 on 2025-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='aids',
            field=models.BooleanField(default=False, help_text='Paciente com AIDS'),
        ),
        migrations.AddField(
            model_name='caso',
            name='dispneia',
            field=models.BooleanField(default=False, help_text='Presença de dispneia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='edema',
            field=models.BooleanField(default=False, help_text='Presença de edema'),
        ),
        migrations.AddField(
            model_name='caso',
            name='faixa_etaria_kalacal',
            field=models.IntegerField(blank=True, choices=[(1, '< 12 meses'), (2, '12-23 meses'), (3, '2-15 anos'), (4, '16-40 anos'), (5, '> 40 anos')], help_text='Faixa etária para cálculo KalaCal', null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='hepatite',
            field=models.BooleanField(default=False, help_text='Presença de hepatite'),
        ),
        migrations.AddField(
            model_name='caso',
            name='ictericia',
            field=models.BooleanField(default=False, help_text='Presença de icterícia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='infeccao',
            field=models.BooleanField(default=False, help_text='Presença de infecção'),
        ),
        migrations.AddField(
            model_name='caso',
            name='insuficiencia_renal',
            field=models.BooleanField(default=False, help_text='Presença de insuficiência renal'),
        ),
        migrations.AddField(
            model_name='caso',
            name='kalacal_habilitado',
            field=models.BooleanField(default=False, help_text='Indica se este caso está habilitado para análise KalaCal'),
        ),
        migrations.AddField(
            model_name='caso',
            name='leucopenia',
            field=models.BooleanField(default=False, help_text='Presença de leucopenia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='plaquetopenia',
            field=models.BooleanField(default=False, help_text='Presença de plaquetopenia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='sitios_sangramento',
            field=models.IntegerField(blank=True, choices=[(1, 'Nenhum'), (2, '1-2 sítios'), (3, '3-4 sítios'), (4, '5-6 sítios')], help_text='Número de sítios de sangramento', null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='vomitos',
            field=models.BooleanField(default=False, help_text='Presença de vômitos'),
        ),
    ]
