# Generated by Django 5.2.2 on 2025-06-08 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_caso_aids_caso_dispneia_caso_edema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='data_notificacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
